version: "3.7"

services:
  database_av_by:
    container_name: database_av_by
    image: sameersbn/postgresql:12-20200524
    environment:
      PG_PASSWORD: $PGPASSWORD
    restart: always
    ports:
      - 5432:5432
    networks:
      - av_by_net
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  tgbot_av_by:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    networks:
      - av_by_net
    env_file:
      - ".env"
    depends_on:
      - database_av_by

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - av_by_net
    volumes:
      - redis-data:/data

networks:
  av_by_net:
    driver: bridge

volumes:
  redis-data:


